version: "3"

services:
  frontend:
    build: frontend
    entrypoint: ./.docker/entrypoint.sh
    container_name: dsmovie-frontend
    volumes:
      - ./frontend:/home/node/app
    ports:
      - 3000:3000

  backend:
    build: backend
    entrypoint: ./.docker/entrypoint.sh
    container_name: dsmovie-backend
    volumes: 
      - ./backend:/app
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    build: .docker/postgres
    container_name: dsmovie-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dsmovie
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: dsmovie-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 9000:80
    extra_hosts:
    - "host.docker.internal:172.17.0.1"